### ISSUE TITLE
ble API for SwitchBot Lock

### ISSUE THREAD

**Issue by martindinicolino** [OpenWonderLabs/SwitchBotAPI-BLE#12]
### Current Situation

whilst the web API has been updated, to allow the SwitchBot Lock to be controlled via an API call (through HomeBridge for example), this functionality is still to be added to the ble API

whilst i am happy with my two SwitchBot Hubs, the current situation means that we are reliant on the web to make these API calls, bringing in additional points of failure and an increased latency over local control

### Proposed Change

please bring the changes implemented in V1.1 to the ble API as well, thus giving us local control

### Additional Context

I‘m not the only person asking for this, for additional context i’ll try to collect some some other places i found, where this issue was brought up:
https://github.com/OpenWonderLabs/SwitchBotAPI-BLE/issues/5
https://github.com/home-assistant/core/issues/68461
https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32/issues/79
https://github.com/OpenWonderLabs/SwitchBotAPI-BLE/issues/8
https://github.com/OpenWonderLabs/homebridge-switchbot/issues/476#issuecomment-1252922093

**Comment by weitheng** [comment]
100% agree on this. Hope that this device will be added for BLE-api support

**Comment by donavanbecker** [comment]
See #5

**Comment by martindinicolino** [comment]
> See #5

what does this mean for the homebridge plugin?

**Comment by donavanbecker** [comment]
@martindinicolino This would need to be implemented into node-SwitchBot for anything to work with Homebridge.

**Comment by martindinicolino** [comment]
@donavanbecker thank you
