### ISSUE TITLE
Thermometer Hygrometer Indoor Outdoor sometimes sends 25 bytes instead of 15

### ISSUE THREAD

**Issue by AdyRock** [OpenWonderLabs/SwitchBotAPI-BLE#30]
### Analysis

When listening to BLE message, the manufacture data for the 'w' device often sends 25 bytes instead of 15 bytes in the packet. When that happens I can't find any data relating to the temperature or humidity.

It seems this is the only type of device to do that and is consistent with all 3 of these devices that I have. Maybe it is some other kind of data be transferred?

### Expected Behavior

I expect to receive a manufacture data packet containing 14 bytes with temperature and humidity in know positions.

### Steps To Reproduce

Listen to BLE broadcasts and monitor the manufacture data.

### Logs

```markdown
Good data:
Updated F3:30:3D:DF:2F:48 @ 8 = w
77 69 50 F3 30 3D DF 2F 48 11 07 87 86 14 00 

Bad data:
Invalid w Manufacture data: size = 25
4C 00 02 15 1B C5 D5 A5 02 00 B8 9F E6 11 4D 22 00 00 A2 CB 08 DF 2F 48 C3
```

### Configuration

```json
Not applicable
```

### Environment

I can see the same issue when using the following:

- BLE packet capture app on my phone,
- Homey BLE monitor,
- ESP32 programmed with Arduino.

**Comment by DigiH** [comment]
Looks like the iBeacon protocol, with possibly the major and minor containing any data, or could it just be a beacon for paring??
