### ISSUE TITLE
WoSensorTHO battery percentage calculation error

### ISSUE THREAD

**Issue by Joe321** [OpenWonderLabs/SwitchBotAPI-BLE#42]
### Analysis

In the WoSensorTHO (Model W3400010) section of the documentation in meter.md, it lists the battery level as "battery_pct = data[5]".  It should be " battery_pct = data[5]  & 0x7F" to strip off unrelated upper bits.

### Expected Behavior

A correct calculation of the battery percentage is the goal.

### Steps To Reproduce

Test on a W3400010 that sets the upper bits of the data[5] field.

### Logs

```markdown
On a new W3400010, my data[5] value is 0xE4 which would be 228% battery.  Using 0xE4 & 0x7F gives 0x64 which would be 100% battery as expected.
```

### Configuration

```json
Raspberry Pi reading data from a new WM3400010.
```

### Environment

- OS:  Raspbian GNU/Linux 9 (stretch)

**Comment by donavanbecker** [comment]
Just updated this, does it look good now?

**Comment by Joe321** [comment]
Looks good.  Thanks.
